syns = {'picket': [u'lookout', u'lookout man', u'sentinel', u'sentry', u'watch', u'spotter'],
'befuddle': [u'confuse', u'bedevil', u'confound', u'discombobulate', u'inebriate', u'intoxicate'],
'besmirch': [u'defame', u'slander', u'smirch', u'denigrate', u'smear', u'sully'],
'twiddle': [u'twirl', u'swirl', u'whirl', u'fiddle with', u'go around', u'manipulate'],
'debauch': [u'corrupt', u'pervert', u'subvert', u'demoralize', u'debase', u'profane'],
'slaver': [u'drivel', u'drool', u'slabber', u'slobber', u'dribble', u'salivate'],
'scotch': [u'thwart', u'queer', u'spoil', u'foil', u'frustrate', u'baffle'],
'exfoliate': [u'break away', u'break off', u'cast off', u'chip', u'chip off', u'shed'],
'shew': [u'demonstrate', u'establish', u'affirm', u'corroborate', u'substantiate', u'support'],
'carom': [u'bounce', u'bound', u'glance', u'recoil', u'reverberate', u'ricochet']}

truth = {'big': ['large','dog','cat','mouse'],
'small': ['little','run','fox','house'],
'male': ['man','philosophy','prime','complex'],
'easy': ['simple','boot','russia','keyboard']}

d0old = {'picket': ['a soldier or a sentry'],
'befuddle': ['cause to become unable to think clearly'],
'besmirch': ['dirty'],
'twiddle': ['to twirl around'],
'debauch': ['to corrupt'],
'slaver': ['drool or liquid coming from your mouth'],
'scotch': ['drink'],
'exfoliate': ['chemical'],
'shew': ['to prove something is correct, affirm'],
'carom': ['a type of seed']}

d0 = {'picket': ['a soldier or a group of soldiers whose duty is to guard something (such as a camp)'],
'befuddle': ['to muddle or stupefy with or as if with drink'],
'besmirch': ['to cause harm or damage to (the reputation of someone or something)'],
'twiddle': ['to turn (something) back and forth slightly'],
'debauch': ['to lead away from virtue or excellence. to corrupt by intemperance or sensuality'],
'slaver': ['to allow liquid to drip out of the mouth'],
'scotch': ['to put an end to (scotched rumors of a military takeover)'],
'exfoliate': ['to cast off in scales, laminae, or splinters'],
'shew': ['to give information that proves (something)'],
'carom': ['a rebounding especially at an angle']}

d1 =  {'picket': ['to stand guard', 'A group of soldiers performing a duty or a group of people protesting.', 'Lock out', 'group of people', 'who stand outside a workplace', 'protest', 'Soldier on guard', 'a body of soldiers serving to guard', 'To enclose, secure, tether, mark out, or fortify with pickets.', 'guardsman'],
 'debauch': ['debase, corrupt', 'to ruin', 'to corrupt or destroy', 'Destroy moral purity', 'to say bad things about someone', 'wasting the purity', 'to demoralize', 'To corrupt by intemperance or sensuality', 'corrupt', 'bad or mischievous'],
 'slaver': ['to take away', 'spit', 'to drip saliva', 'A person who dealt in or owned slaves.', 'group of leaders', 'Salivate', 'a person who dealt in or owned slaves.', '"These unpopulated regions had been a haven for pirates, slavers , and other scoundrels for centuries."', 'salivate', 'Salivate, drool'],
 'shew': ['way to say show', 'cast away', 'throw off', 'To show.', 'shed', 'to show, demonstrate', 'To show something', 'to shed off in peices', 'to prove something is correct, affirm', 'to show'],
 'twiddle': ['to fiddle with, and fuss with', 'to mess with your hands(fiddle your thumb)', 'an act of twisting or fiddling with something.', 'gesticulate in idle manner, twirl', 'twirl something around.', 'fiddle', 'to move in a pattern', 'To turn something back and forth slightly', 'To move back and forth slightly', 'twirl'],
 'befuddle': ['fiddle', "SHE BEFUDDLE'S ME", '"he has an air of befuddled unworldliness"', 'to confuse another', 'cause to become unable to think clearly', 'to confuse, bewilder', 'Make drunk', 'confuse', 'Cause to become unable to think clearly.', 'To confuse'],
 'exfoliate': ['Chipping, splintering, scaling from a surface', 'to remove', 'to break off in splinters, cast off', 'Peel off', 'to take away dead skin', 'layer off', "i didn't know full detail about vocabulary but is good", '"the bark exfoliates in papery flakes"', 'To clean', 'to shed'],
 'carom': ['good thing', 'insert a disc', 'means round', 'rebound', 'soldire', 'rebound, support', 'to rebound', 'To bounce', 'Pool game', 'to ricochet or recoil'],
 'scotch': ['To prevent', 'To put an end to something (as in a plan)', 'to cut off', 'to stop', 'to get away', 'Alcohol', 'to disprove a theory', 'scotch is alcohl athing', 'to injure as in cutting', 'end off'],
 'besmirch': ['I dont know', 'damage reputation', 'to lessen the opinion of', 'damage', 'Dirty.', "i didn't know", 'to hurt someone socially', '"he had besmirched the good name of his family"', 'Damage reputation of some one', 'talk badly about']}

d2 =  {'picket': ['watch', 'to stand in watch', 'A sentinel.', 'pick', 'troops', 'A post', 'action', 'To stand guard over', 'Someone standing guard', 'post'],
 'debauch': ['corrupt', 'to debase or corrupt', 'corrupt', 'warp', 'launch', 'dept', 'to corrupt', 'differentiate', 'to mess something up', 'to destroy or overindulge'],
 'slaver': ['Drool', 'slave', 'a liquid from mouth', 'drool', 'Slobber or drool', 'To drool or slobber', 'servitude', 'Person who own slaves', 'to produce saliva', 'drool'],
 'shew': ['sentinel', 'clear', 'back up', 'Evince, display for others to see.', 'To show; demonstrate.', 'show', 'to show', 'to push away', 'shewd', 'Do without'],
 'twiddle': ['to while away time', 'To whirl.', 'fiddle with', 'twirl around', 'to move rhythmically', 'twirl', 'Dee', 'Twist around', 'twirl', 'Turn around'],
 'befuddle': ['Unable to think clearly', 'Stump', 'cause to become unable to think clearly.', 'unable to think', 'Confuse.', 'to confuse the issues', 'to make less clear', 'To confuse', 'confuse', 'to confuse'],
 'exfoliate': ['this is nice to work.', 'chemica', 'shed', 'Cause to shed materials', 'Remove the top layer of', 'to rub off or shed off', 'to slough off', 'remove foliage', 'take off', 'scrape off'],
 'carom': ['to ricochet or rebound', 'board', 'seed', 'type of seed', '1. (noun) A seed. 2. (verb) To rebound off of a surface.', 'a type of seed', 'bounce off something', 'seed', 'a type of seed', 'To glance off.'],
 'scotch': ['To crush', 'To thwart.', 'A form of whiskey made in Scotland', 'decisively put an end to', 'high', 'put a stop to', 'drink', 'to put an end to', 'nip in the bud', 'scratch'],
 'besmirch': ['defame', 'to dirty', 'Damage', 'smear', 'desire', 'tarnish', 'to destroy or deceive the issue', 'To make unclean', 'To dirty', 'better']}

d3 =  {'picket': ['fdgdfg', 'a protestor', 'group that joins forces', 'a sentinel or something that watches', 'stand guard', 'To protest against something', 'stand for or against'],
 'debauch': ['destroy', 'To make lower, to profane', 'to defame', 'to corrupt something', 'corrupting', 'to corrupt something', 'make sullied', 'To slander ', 'abuse', 'mess up'],
 'shew': ['show', 'A lookout or watchman.', 'salivate', 'past tense of show', 'to show someone something', 'to take off', 'throw off', 'To show', 'shed', 'to show'],
 'befuddle': ['confuse', 'To confuse', 'to confuse', 'a person unable to think', 'cause confusion', 'something to confuse', 'confuse', 'to confuse', 'fluster', 'confuse'],
 'twiddle': ['To play around with, with motion.', 'to waste time', 'to turn back an object', 'to turn around and around', 'to take care', 'fool with', 'To move something around absently', 'tamper', 'twirl'],
 'slaver': ['A person who owned slaves', 'Someone who owns slaves.', 'someone who owns slaves', 'head of slaves', "someone who takes another person's freedom", 'to be a serve man', 'one who owns slaves', 'someone who sells slaves', 'fawn', 'someone who owns slaves'],
 'exfoliate': ['tea', 'To rub away a layer of, as with skin.', 'to remove the top layer', 'to seperate and join again', 'remove dirty layers', 'to remove the surface', 'remove dead cells', 'To remove the top layer', 'shed', 'remove top layer'],
 'carom': ['a board game', 'to strike', "it's used in pool", 'a seed pod', 'A seed', 'seed'],
 'scotch': ['someone', 'To smash.', 'to break', 'fight', 'throw off', 'sparing', 'crush'],
 'besmirch': ['damages', 'To lower the reputation of, to lower', 'a scowl', 'make someone look bad', 'belittle and sully', 'defile', 'destroy or deceive']}
